#name, main, version and api are required
name: ExamplePlugin
main: ExamplePlugin\MainClass
src-namespace-prefix: ExamplePlugin
version: 1.4.1+dev
api: 5.4.0

load: POSTWORLD
author: Tanmay
description: Example plugin showing the new API
website: https://github.com/Tanmayboy/minionpm5-test/
commands:
  example:
    description: Example command
    usage: "/example"
    permission: exampleplugin.command.example
permissions:
  exampleplugin.command.example:
    description: "Allows the user to run the example command"
    default: true
