name: Build Phar Archive

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4  # Adjust the PHP version as needed

      - name: Install Composer Dependencies
        run: composer install  # Use 'composer.json' in your repository

      - name: Create Phar Archive
        run: php build.php  # Replace with the actual build script

      - name: Upload Phar Archive
        uses: actions/upload-artifact@v2
        with:
          name: plugin-phar
          path: path/to/your/phar/directory  # Adjust the path to your Phar
